---
title: "My First Reproducible Report"
format:
    html:
        number-sections: true
execute:
  echo: false
  warning: true
  message: true
---

```{r}
#| label: load-library
#| echo: false
#| message: false
#| warning: false

library(ggplot2)
library(knitr)
library(tidyverse)

flu_data <- read_csv("avian_influenza_numbers.csv")

```

# First quarto doc on git {#sec-first}

I'm learning how to use Github. This is in @sec-first. Next is @sec-subheading1.

## This subsection I'm making on a branch

Wow I'm a subsection

This one is on my second branch

## Now it has a subheading {#sec-subheading1}

```{r}
#| label: fig-scatterplot
#| fig-cap: "Normalised mileage of cars. Positive values represent above average mileage, negative values indicate negative mileage"


library(ggplot2)
library(knitr)

data("mtcars")  # load data
mtcars$`car name` <- rownames(mtcars)  # create new column for car names
mtcars$mpg_z <- round((mtcars$mpg - mean(mtcars$mpg))/sd(mtcars$mpg), 2)  # compute normalized mpg
mtcars$mpg_type <- ifelse(mtcars$mpg_z < 0, "below", "above")  # above / below avg flag
mtcars <- mtcars[order(mtcars$mpg_z), ]  # sort
mtcars$`car name` <- factor(mtcars$`car name`, levels = mtcars$`car name`)  # convert to factor to retain sorted order in plot.

# Diverging Barcharts
ggplot(mtcars, aes(x=`car name`, y=mpg_z, label=mpg_z)) + 
  geom_bar(stat='identity', aes(fill=mpg_type), width=.5)  +
  scale_fill_manual(name="Mileage", 
                    labels = c("Above Average", "Below Average"), 
                    values = c("above"="#00ba38", "below"="#f8766d")) + 
  labs(subtitle="Normalised mileage from 'mtcars'", 
       title= "Diverging Bars", x="Normalised mileage", y="Car Name") + 
  coord_flip()
```

In @fig-scatterplot we can see some green and salmon bars.

But in @tbl-summarytable you can see a data summary.

```{r}
#| label: tbl-summarytable
#| tbl-cap: Summary of the dataset

minimal_data <- flu_data |>
  select(Range, Vietnam, Turkey, Egypt) |>
  dplyr::filter(Range == "1997-1999")
kable(minimal_data)
```

